version: '3.8'
services:
    web:
      image: mariadziuba/lab4_bd:latest
      ports:
        - 8001:8001
      env_file:
        - .env
      depends_on:
        - clickhouse
       
    clickhouse:
      image: clickhouse/clickhouse-server
      ports:
        - 9000:9000
        - 8123:8123
        - 9009:9009
      environment:
        - CLICKHOUSE_USER=${CLICKHOUSE_LOGIN}
        - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PWD}

    kafka:
      image: bitnami/kafka:latest
      ports:
        - "9092:9092"
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        - KAFKA_TOPIC_NAME=${TOPIC_NAME}
        - KAFKA_TOPIC_PARTITIONS=${PARTITIONS_COUNT}
      depends_on:
        - zookeeper

    zookeeper:
      image: bitnami/zookeeper:3.9
      ports:
        - "2181:2181"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes

    kafka_consumer:
      build: . 
      command: ["python", "src/consumer.py"]
      restart: unless-stopped
      depends_on:
        - kafka
        - clickhouse
        - web
      